# Generated by Django 5.1.4 on 2025-07-02 21:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vibration_source", models.CharField(blank=True, max_length=100)),
                (
                    "hand",
                    models.CharField(
                        choices=[("left", "Lewa ręka"), ("right", "Prawa ręka")],
                        max_length=50,
                    ),
                ),
                (
                    "measurement_time",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "round_up_to",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("ahwx", models.FloatField(blank=True, null=True)),
                ("ahwy", models.FloatField(blank=True, null=True)),
                ("ahwz", models.FloatField(blank=True, null=True)),
                ("vector_summ", models.FloatField(blank=True, null=True)),
                ("partial_exposure", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "activitie",
                "verbose_name_plural": "activities",
                "ordering": ("measurement_time",),
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ax",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "ay",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "az",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="calculator.activity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "measurements",
            },
        ),
    ]
