# Generated by Django 5.2.2 on 2025-07-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_indicator_alter_activity_options_activity_cai_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="vibration_source",
            new_name="description_source_measuring",
        ),
    ]
