# Generated by Django 5.1.4 on 2025-07-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0002_indicator_alter_measurement_ax_alter_measurement_ay_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="vector_summ_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
