# Generated by Django 5.1.4 on 2025-07-03 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_activity_vector_summ_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicator",
            old_name="Action_threshold_multiplicity",
            new_name="Action_threshold_multiplicity_lh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="daily_exposure",
            new_name="Action_threshold_multiplicity_rh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="exposure_30_less",
            new_name="daily_exposure_lh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="multiplicity_NDN",
            new_name="daily_exposure_rh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="multiplicity_pregnant_breastfeeding",
            new_name="exposure_30_less_lh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="multiplicity_young",
            new_name="exposure_30_less_rh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="left_hand_exposure_time",
            new_name="exposure_time_lh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="right_hand_exposure_time",
            new_name="exposure_time_rh",
        ),
        migrations.AddField(
            model_name="indicator",
            name="multiplicity_NDN_lh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="multiplicity_NDN_rh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="multiplicity_pregnant_breastfeeding_lh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="multiplicity_pregnant_breastfeeding_rh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="multiplicity_young_lh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="multiplicity_young_rh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
