# Generated by Django 5.2.2 on 2025-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0003_rename_vibration_source_activity_description_source_measuring",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description_source_measuring",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Wykonywana czynność / źródło drgań / warunki pomiarów",
            ),
        ),
    ]
