# Generated by Django 5.1.4 on 2025-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0004_rename_action_threshold_multiplicity_indicator_action_threshold_multiplicity_lh_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-hand", "measurement_time"),
                "verbose_name": "activitie",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="Action_threshold_multiplicity_lh",
            new_name="action_threshold_multiplicity_lh",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="Action_threshold_multiplicity_rh",
            new_name="action_threshold_multiplicity_rh",
        ),
    ]
