# Generated by Django 5.2.2 on 2025-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_alter_activity_hand"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="act_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="2. Nazwa czynności"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description_source_measuring",
            field=models.CharField(
                blank=True,
                max_length=250,
                verbose_name="1. Wykonywana czynność / źródło drgań / warunki pomiarów",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="hand",
            field=models.CharField(
                choices=[("left", "Lewa ręka"), ("right", "Prawa ręka")],
                max_length=50,
                verbose_name="2. Miejsce, orientacja osi oraz metoda mocowania przetwornika",
            ),
        ),
    ]
