# Generated by Django 5.1.4 on 2025-07-04 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="bg20_l",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="bg20_r",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
