# Generated by Django 5.2.2 on 2025-07-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0006_activity_act_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="act_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="3. Nazwa czynności"
            ),
        ),
    ]
