# Generated by Django 5.1.4 on 2025-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0007_indicator_ba17_l_indicator_ba17_r_indicator_bg17_l_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="rounded_vector_summ",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
