# Generated by Django 5.2.2 on 2025-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0007_alter_activity_act_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-hand", "measurement_time_Ti"),
                "verbose_name": "activities",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="measurement_time",
            new_name="measurement_time_Ti",
        ),
        migrations.AlterField(
            model_name="activity",
            name="act_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="3. Nazwa czynności:"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description_source_measuring",
            field=models.CharField(
                blank=True,
                max_length=250,
                verbose_name="1. Wykonywana czynność / źródło drgań / warunki pomiarów:",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="hand",
            field=models.CharField(
                choices=[("left", "Lewa ręka"), ("right", "Prawa ręka")],
                max_length=50,
                verbose_name="2. Miejsce, orientacja osi oraz metoda mocowania przetwornika:",
            ),
        ),
    ]
