# Generated by Django 5.2.2 on 2025-07-10 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0008_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="time_Tp",
            field=models.IntegerField(
                default=1,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="4. Czas trwania pomiaru Tp [min]:",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="measurement_time_Ti",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="4. Czas ekspozycji Ti [min]:",
            ),
        ),
    ]
