# Generated by Django 5.1.4 on 2025-07-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0008_activity_rounded_vector_summ"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="rounded_ahwx",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="rounded_ahwy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="rounded_ahwz",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
