# Generated by Django 5.2.2 on 2025-07-10 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_activity_time_tp_alter_activity_measurement_time_ti"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="b_type_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="6. Wartość niepewności typu B:"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="7. Uwagi:"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="measurement_time_Ti",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="5. Czas ekspozycji Ti [min]:",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="round_up_to",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="8. Ilośc miejsc po przecinku:",
            ),
        ),
    ]
