# Generated by Django 5.1.4 on 2025-07-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0009_activity_rounded_ahwx_activity_rounded_ahwy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="s_axis_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="s_axis_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="s_axis_z",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
