# Generated by Django 5.1.4 on 2025-07-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_activity_s_axis_x_activity_s_axis_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="uprobkj_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="uprobkj_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="uprobkj_z",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
