# Generated by Django 5.2.2 on 2025-07-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_activity_b_type_value_activity_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description_source_measuring",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="1. Wykonywana czynność / źródło drgań / warunki pomiarów:",
            ),
        ),
    ]
