# Generated by Django 5.2.2 on 2025-07-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0011_alter_activity_description_source_measuring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="calculator.activity",
                verbose_name="1. Wybierz czynnośc:",
            ),
        ),
    ]
