# Generated by Django 5.1.4 on 2025-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0011_activity_uprobkj_x_activity_uprobkj_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="ucj_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="ucj_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="ucj_z",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
