# Generated by Django 5.1.4 on 2025-07-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0012_activity_ucj_x_activity_ucj_y_activity_ucj_z"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="uhvi",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
