# Generated by Django 5.1.4 on 2025-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0013_activity_uhvi"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cai",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
