# Generated by Django 5.1.4 on 2025-07-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0014_activity_cai"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="caiuci2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
