# Generated by Django 5.1.4 on 2025-07-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0015_activity_caiuci2"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cti",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="uti_lh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="uti_rh",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
