# Generated by Django 5.1.4 on 2025-07-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0016_activity_cti_activity_uti_lh_activity_uti_rh"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="ctiuti2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
