# Generated by Django 5.1.4 on 2025-07-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0017_activity_ctiuti2"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="uca8",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
