# Generated by Django 5.1.4 on 2025-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0018_activity_uca8"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="_2xuca8",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="daily_exposure",
            field=models.TextField(blank=True, null=True),
        ),
    ]
