# Generated by Django 5.1.4 on 2025-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0019_activity__2xuca8_activity_daily_exposure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="daily_exposure_lh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="daily_exposure_rh",
            field=models.TextField(blank=True, null=True),
        ),
    ]
