# Generated by Django 5.1.4 on 2025-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0020_alter_indicator_daily_exposure_lh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="uahv",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
