# Generated by Django 5.1.4 on 2025-07-07 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0021_activity_uahv"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="ucahvmax_l",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="ucahvmax_r",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
