# Generated by Django 5.1.4 on 2025-07-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0022_indicator_ucahvmax_l_indicator_ucahvmax_r"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="exposure_30_less_lh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="exposure_30_less_rh",
            field=models.TextField(blank=True, null=True),
        ),
    ]
