# Generated by Django 5.1.4 on 2025-07-08 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0023_alter_indicator_exposure_30_less_lh_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-hand", "measurement_time"),
                "verbose_name": "activities",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.RemoveField(
            model_name="activity",
            name="_2xuca8",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="daily_exposure",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="uca8",
        ),
        migrations.AddField(
            model_name="indicator",
            name="_2xuca8_l",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="_2xuca8_r",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicator",
            name="uca_8_l",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="uca_8_r",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
